dist: trusty
language: java
jdk: oraclejdk8
notifications:
  email: false
env:
  global:
  - TERM=dumb

install: ./gradlew build -S

cache:
  directories:
    - '$HOME/.m2'
    - '$HOME/.gradle'
before_cache:
    - rm -f $HOME/.gradle/caches/*/*.lock

deploy:
  - provider: script
    skip_cleanup: true
    script: ./gradlew uploadArchives -S
    on:
      all_branches: true
      repo: CyclopsMC/IntegratedDynamics-Compat
      condition: "$TRAVIS_BRANCH =~ ^(master|release).*$"
