modLoader="javafml"
loaderVersion="[44,)"
issueTrackerURL="https://github.com/CyclopsMC/IntegratedDynamics-Compat/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/integrateddynamicscompat"
license="MIT"
logoFile="logo.png"
authors="rubensworks (aka kroeser)"
[[mods]]
modId="integrateddynamicscompat"
version="${file.jarVersion}"
displayName="IntegratedDynamics-Compat"
description='''
Integrated Dynamics compatibility with other mods.
'''
[[dependencies.integrateddynamicscompat]]
    modId="cyclopscore"
    mandatory=true
    versionRange="[1.17.3,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integrateddynamicscompat]]
    modId="forge"
    mandatory=true
    versionRange="[44.1.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integrateddynamicscompat]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,]"
    ordering="NONE"
    side="BOTH"
[[dependencies.integrateddynamicscompat]]
    modId="integrateddynamics"
    mandatory=true
    versionRange="[1.11.8,)"
    ordering="AFTER"
    side="BOTH"
