modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/CyclopsMC/IntegratedDynamics-Compat/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/integrateddynamicscompat"
license="MIT"
logoFile="logo.png"
authors="rubensworks (aka kroeser)"
[[mods]]
modId="integrateddynamicscompat"
version="${file.jarVersion}"
displayName="IntegratedDynamics-Compat"
description='''
Integrated Dynamics compatibility with other mods.
'''
[[dependencies.integrateddynamicscompat]]
    modId="cyclopscore"
    type="required"
    versionRange="[1.25.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integrateddynamicscompat]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integrateddynamicscompat]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1,]"
    ordering="NONE"
    side="BOTH"
[[dependencies.integrateddynamicscompat]]
    modId="integrateddynamics"
    type="required"
    versionRange="[1.23.2,)"
    ordering="AFTER"
    side="BOTH"
